[tool.poetry]
name = "repl_python3_pokeclient"
version = "0.1.0"
description = ""
authors = ["FEOU <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
